image: python:3.7

stages:
  - typing
  - test

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -r requirements.txt

mypy:
  stage: typing
  script:
    - python -m mypy cloudsync --ignore-missing-imports
  allow_failure: true

tests:
  stage: test
  script:
    - python -m pytest --cov=cloudsync tests
  coverage: '/TOTAL.*\s+(\d+%)$/'
